### ISSUE TITLE
What's the status of AIL?

### ISSUE THREAD

**Issue by dgrahn** [angr/ailment#34]
What is the status of this IR? It looks like it has some potential, but has no development effort.

**Comment by rhelmot** [comment]
It is being used! the core IR is very stable and doesn't really get touched much these days, but over in angr/angr we are working on analyses that actually use it. Don't quote me on this, but I'm pretty sure what you want is in angr/analyses/decompiler.

**Comment by dgrahn** [comment]
@rhelmot How do you actually access the AIL IR? I can get to VEX from a block, but AIL isn't a part of the block.

**Comment by rhelmot** [comment]
That would be part of ailment :) https://github.com/angr/ailment/blob/b8bacaa65480cffb8056fd44d2fa4627ea1832b3/ailment/converter.py#L219

**Comment by ltfish** [comment]
AIL is designed to be an IL that incorporates both low-level artifacts (registers, memory, instruction addresses) and high-level abstractions (function summaries, loop summaries, and even human user input) to achieve the following goals:

- Faster symbolic emulation.
- Mixed emulation of code from different architectures.
- Faithful decompilation.

I wouldn't say AIL is stable. In fact, a lot of planned AIL things haven't been implemented yet. But it is definitely being actively used by angr components like the decompiler.
