### ISSUE TITLE
_md5 ImportError on some Python distributions

### ISSUE THREAD

**Issue by recursiveMake** [angr/ailment#71]
There's an error importing ailment on some distributions that don't have _md5. In my case, Python 3.6 on RHEL 7.

See [here](https://github.com/angr/claripy/issues/230).

I'll open a PR where we fall back to the slower hashlib version of md5.

**Comment by ltfish** [comment]
Oh thanks! I totally forgot about that issue you opened in claripy when I was implementing the stable hash in ailment...
